export const API_SERVICES_BASE_URL = 'API_SERVICES_BASE_URL';
export const DOMAIN_NAME = 'DOMAIN_NAME';
export const AUTH_COOKIE_NAME = 'AUTH_COOKIE_NAME';
export const COOKIE_ACCEPTED_COOKIE_NAME = 'COOKIE_ACCEPTED_COOKIE_NAME'
